name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'
    - uses: pnpm/action-setup@v4.0.0
    - name: install, build, and test
      run: |
        pnpm install
        pnpm build
        pnpm test
      env:
        CI: true
